#!/bin/bash
{% from "mayan/map.jinja" import server with context %}

NAME="mayan"
DJANGODIR={{ server.dir.base }}/site
USER=mayan
GROUP=mayan
NUM_WORKERS={{ server.workers }}
DJANGO_SETTINGS_MODULE=local_settings
DJANGO_WSGI_MODULE=wsgi

#echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source {{ server.dir.base }}/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec {{ server.dir.base }}/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --pid=/tmp/mayan \
  --bind={{ server.bind.address }}:{{ server.bind.port }}